### PR TITLE
Discussion PR: propose [temporary] removal of LiveView for eventual consistency

### PR DESCRIPTION
**Pull request by bjornrud**
Disclaimer: I'm reading and working through the LiveView book for the first time

Asking if people think hands should be stayed here.   To my taste, this makes sense to 🔪 because it sets expectations with new entrants and outside parties.  When I saw it, felt disingenuous.

In no way precludes adding it back at a different time, or someone veto-ing.  Can imagine arguments like, "well, we use it in soooome places..." which is defy a valid take, but not normative to my 👂.

### CODE REVIEW

**Comment by bjornrud** [comment]
Screen Shot 2022-09-20 at 9 47 19 AM

Is how it looks to people facing the organization from the public interwebs

**Review by tonyvanriet — APPROVED** [review]
I'm not opposed to taking it out, mostly since I don't think it's a necessary detail... it's part of Phoenix. But I could see others that are more focused on front-end considering it necessary detail.

I don't feel it's disingenuous though, as it has been our default for new UI development for a good while now, via `harness_pixel`. Might even be in the majority by now in terms of user activity in Relay compared to Vue, vanilla Phoenix, et al.

No opposed, so `Approve`, but would change my mind if those focused on front-end felt it was an important signal to the outside world.

**Comment by jlnfi** [comment]
nice!! is that the [book from pragprog](https://pragprog.com/titles/liveview/programming-phoenix-liveview/)? what do you think of it so far?

i think the only UI app in Relay that _isn't_ LiveView-driven is `relay_web` (if i had to guess, i'd say there are maybe ~12 UI apps that contribute to "doing things in Relay") - in light of that, does it still feel disingenuous?

**Comment by bjornrud** [comment]
@jlnfi aye, it still does and trying to put my finger on why

running limping

**Comment by bjornrud** [comment]
Bah, whatever. Just a feeling, I guess. Bigger fish.  Thanks y'all.

**Pull request closed without merging**
